In [6]:
#Importing required library
import requests
import pandas as pd
import os
import numpy as np

#APIKEY path
#path = 'C:/Users/ddamo/Desktop/3rd Evoleon/MOP-Code/env.txt'
envar = open(path,'r')
Envar2 = envar.read()

Base_url = ('https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/')
APIKEY = (Envar2)

response = requests.get(f'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/trees-with-species-and-dimensions-urban-forest/records?limit=100')
data = response.json()

ID = []
for result in data['results']:
    ID.append({
        'Name': result['common_name'],
        'Scientific Name': result["genus"],
        'Geo location': result['geolocation'],
    })

df = pd.DataFrame(ID)

In [2]:
import pandas as pd
import os
import requests

def fetch_data(base_url, dataset,api_key, num_records=99, offset= 0):
    all_records = [] 
    max_offset = 9999 # Maximum number of requests
    while True:
        # maximum limit check
        if offset > max_offset:
            break
# Create API request URL
        filters = f'{dataset}/records?limit={num_records}&offset={offset}'
        url = f' {base_url}{filters}&api_key={api_key}'
        
        # Start request
        try:
            result = requests.get(url, timeout=10)
            result. raise_for_status()
            records = result.json().get('results')
        except requests.exceptions.RequestException as e:
            raise Exception(f"API request failed: {e}")
        if records is None:
            break
        
        all_records.extend(records)
        if len(records) < num_records:
            break
            
        offset += num_records
        
        # next cycle offset offset + num_records
        # DataFrame all data
        
    df = pd.DataFrame(all_records)
    return df

In [3]:
Treedataset= 'trees-with-species-and-dimensions-urban-forest'
df = fetch_data(Base_url,Treedataset,APIKEY)
print(df)

NameError: name 'Base_url' is not defined

In [138]:
treelink = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/trees-with-species-and-dimensions-urban-forest/exports/csv?lang=en&timezone=Australia%2FSydney&use_labels=true&delimiter=%2C&quote_all=false&with_bom=true'
tree_df = pd.read_csv(treelink)
tree_df

Carbonlink= 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/microlabs-co2-sensor-data/exports/csv?lang=en&timezone=Australia%2FSydney&use_labels=true&delimiter=%2C'
Carbon_df = pd.read_csv(treelink)
Carbon_df

,CoM ID,Common Name,Scientific Name,Genus,Family,Diameter Breast Height,Year Planted,Date Planted,Age Description,Useful Life Expectency,Useful Life Expectency Value,Precinct,Located in,UploadDate,CoordinateLocation,Latitude,Longitude,Easting,Northing,geolocation
0,1440992,River red gum,Eucalyptus camaldulensis,Eucalyptus,Myrtaceae,NaN,2009,2009-12-14,NaN,NaN,NaN,NaN,Park,2021-01-10,"-37.789042536009, 144.94750113149306",-37.789043,144.947501,319271.37,5815606.69,"-37.789042536009, 144.94750113149306"
1,1286119,River red gum,Eucalyptus camaldulensis,Eucalyptus,Myrtaceae,80.0,2008,2008-07-16,Mature,31-60 years,60.0,NaN,Park,2021-01-10,"-37.78989006812276, 144.9256959906416",-37.789890,144.925696,317353.24,5815470.25,"-37.78989006812276, 144.9256959906416"
2,1439848,European nettle tree,Celtis australis,Celtis,Cannabaceae,4.0,2009,2009-09-08,Juvenile,31-60 years,60.0,NaN,Street,2021-01-10,"-37.795227592098875, 144.91940533967247",-37.795228,144.919405,316812.46,5814865.65,"-37.795227592098875, 144.91940533967247"
3,1584631,Swamp Sheoak,Casuarina obesa,Casuarina,Casuarinaceae,NaN,2015,2015-06-18,NaN,NaN,NaN,NaN,Park,2021-01-10,"-37.795178798251044, 144.95235531785673",-37.795179,144.952355,319713.76,5814935.15,"-37.795178798251044, 144.95235531785673"
4,1286271,Golden Poplar,Populus x canadensis,Populus,Salicaceae,35.0,2008,2008-12-18,Semi-Mature,31-60 years,60.0,NaN,Street,2021-01-10,"-37.7904175404039, 144.92779056976474",-37.790418,144.927791,317538.99,5815415.81,"-37.7904175404039, 144.92779056976474"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76923,1526689,Red Box,Eucalyptus polyanthemos,Eucalyptus,Myrtaceae,NaN,2013,2013-01-22,NaN,NaN,NaN,NaN,Park,2021-01-10,"-37.77968423847431, 144.96217220362632",-37.779684,144.962172,320540.70,5816673.41,"-37.77968423847431, 144.96217220362632"
76924,1783637,Lightwood Wattle,Acacia implexa,Acacia,Fabaceae,NaN,2020,2020-05-19,NaN,NaN,NaN,NaN,Park,2021-01-10,"-37.781052359602995, 144.95237974656814",-37.781052,144.952380,319681.57,5816502.75,"-37.781052359602995, 144.95237974656814"
76925,1023894,London Plane,Platanus x acerifolia,Platanus,Platanaceae,18.0,1899,1999-12-30,Semi-Mature,11-20 years,20.0,NaN,Street,2021-01-10,"-37.8092487661872, 144.96541492209963",-37.809249,144.965415,320897.72,5813398.98,"-37.8092487661872, 144.96541492209963"
76926,1287085,Jacaranda,Jacaranda mimosifolia,Jacaranda,Bignoniaceae,6.0,2008,2008-08-25,Juvenile,11-20 years,20.0,NaN,Street,2021-01-10,"-37.83631076544197, 144.98513657513598",-37.836311,144.985137,322698.76,5810433.65,"-37.83631076544197, 144.98513657513598"
76927,1783452,Lemon scented myrtle,Backhousia citriodora,Backhousia,Myrtaceae,NaN,2020,2020-12-05,NaN,NaN,NaN,NaN,Park,2021-01-10,"-37.81621736150108, 144.9801744499791",-37.816217,144.980174,322213.84,5812653.90,"-37.81621736150108, 144.9801744499791"

In [115]:

print(tree_df)

        CoM ID           Common Name           Scientific Name       Genus  \
0      1440992         River red gum  Eucalyptus camaldulensis  Eucalyptus
1      1286119         River red gum  Eucalyptus camaldulensis  Eucalyptus
2      1439848  European nettle tree          Celtis australis      Celtis
3      1584631          Swamp Sheoak           Casuarina obesa   Casuarina
4      1286271         Golden Poplar      Populus x canadensis     Populus
...        ...                   ...                       ...         ...
76923  1526689               Red Box   Eucalyptus polyanthemos  Eucalyptus
76924  1783637      Lightwood Wattle            Acacia implexa      Acacia
76925  1023894          London Plane     Platanus x acerifolia    Platanus
76926  1287085             Jacaranda     Jacaranda mimosifolia   Jacaranda
76927  1783452  Lemon scented myrtle     Backhousia citriodora  Backhousia

              Family  Diameter Breast Height  Year Planted Date Planted  \
0          Myrtaceae                     NaN          2009   2009-12-14
1          Myrtaceae                    80.0          2008   2008-07-16
2        Cannabaceae                     4.0          2009   2009-09-08
3      Casuarinaceae                     NaN          2015   2015-06-18
4         Salicaceae                    35.0          2008   2008-12-18
...              ...                     ...           ...          ...
76923      Myrtaceae                     NaN          2013   2013-01-22
76924       Fabaceae                     NaN          2020   2020-05-19
76925    Platanaceae                    18.0          1899   1999-12-30
76926   Bignoniaceae                     6.0          2008   2008-08-25
76927      Myrtaceae                     NaN          2020   2020-12-05

      Age Description Useful Life Expectency  Useful Life Expectency Value  \
0                 NaN                    NaN                           NaN
1              Mature            31-60 years                          60.0
2            Juvenile            31-60 years                          60.0
3                 NaN                    NaN                           NaN
4         Semi-Mature            31-60 years                          60.0
...               ...                    ...                           ...
76923             NaN                    NaN                           NaN
76924             NaN                    NaN                           NaN
76925     Semi-Mature            11-20 years                          20.0
76926        Juvenile            11-20 years                          20.0
76927             NaN                    NaN                           NaN

       Precinct Located in  UploadDate  \
0           NaN       Park  2021-01-10
1           NaN       Park  2021-01-10
2           NaN     Street  2021-01-10
3           NaN       Park  2021-01-10
4           NaN     Street  2021-01-10
...         ...        ...         ...
76923       NaN       Park  2021-01-10
76924       NaN       Park  2021-01-10
76925       NaN     Street  2021-01-10
76926       NaN     Street  2021-01-10
76927       NaN       Park  2021-01-10

                            CoordinateLocation   Latitude   Longitude  \
0         -37.789042536009, 144.94750113149306 -37.789043  144.947501
1        -37.78989006812276, 144.9256959906416 -37.789890  144.925696
2      -37.795227592098875, 144.91940533967247 -37.795228  144.919405
3      -37.795178798251044, 144.95235531785673 -37.795179  144.952355
4        -37.7904175404039, 144.92779056976474 -37.790418  144.927791
...                                        ...        ...         ...
76923   -37.77968423847431, 144.96217220362632 -37.779684  144.962172
76924  -37.781052359602995, 144.95237974656814 -37.781052  144.952380
76925    -37.8092487661872, 144.96541492209963 -37.809249  144.965415
76926   -37.83631076544197, 144.98513657513598 -37.836311  144.985137
76927    -37.81621736150108, 144.9801744499791 -37.816217  144.980174

         Easting    Northing                              geolocation
0      319271.37  5815606.69     -37.789042536009, 144.94750113149306
1      317353.24  5815470.25    -37.78989006812276, 144.9256959906416
2      316812.46  5814865.65  -37.795227592098875, 144.91940533967247
3      319713.76  5814935.15  -37.795178798251044, 144.95235531785673
4      317538.99  5815415.81    -37.7904175404039, 144.92779056976474
...          ...         ...                                      ...
76923  320540.70  5816673.41   -37.77968423847431, 144.96217220362632
76924  319681.57  5816502.75  -37.781052359602995, 144.95237974656814
76925  320897.72  5813398.98    -37.8092487661872, 144.96541492209963
76926  322698.76  5810433.65   -37.83631076544197, 144.98513657513598
76927  322213.84  5812653.90    -37.81621736150108, 144.9801744499791

[76928 rows x 20 columns]

In [116]:
Trep = pd.DataFrame()
Trep['Common Name']= tree_df['Common Name']
Trep['Genus']= tree_df['Genus']
Trep['Family']= tree_df['Family']
Trep['Location']= tree_df["geolocation"]

In [122]:
#print(Trep)

S =pd.DataFrame()
S = Trep.drop_duplicates(subset="Genus")
print(S)

                 Common Name          Genus         Family  \
0              River red gum     Eucalyptus      Myrtaceae
2       European nettle tree         Celtis    Cannabaceae
3               Swamp Sheoak      Casuarina  Casuarinaceae
4              Golden Poplar        Populus     Salicaceae
5          Lemon Scented Gum       Corymbia      Myrtaceae
...                      ...            ...            ...
65905                    NaN            NaN            NaN
67693           Black Bamboo  Phyllostachys        Poaceae
68157       Bentham's cornel         Cornus      Cornaceae
70310          Native quince      Alectryon    Sapindaceae
71162  European Mountain Ash         Sorbus       Rosaceae

                                      Location
0         -37.789042536009, 144.94750113149306
2      -37.795227592098875, 144.91940533967247
3      -37.795178798251044, 144.95235531785673
4        -37.7904175404039, 144.92779056976474
5       -37.826652334719014, 144.9828325497969
...                                        ...
65905   -37.77669534323479, 144.94047608472198
67693  -37.830941050841716, 144.97258215313335
68157   -37.81442544553981, 144.97971665595654
70310   -37.82478954047682, 144.97511158831483
71162  -37.828583040415786, 144.96690711677977

[171 rows x 4 columns]

In [ ]:
import requests
import pandas as pd
import numpy as np
from IPython.display import display
from IPython.display import HTML
import re
import folium

pd.set_option('display.max_columns', None)  
pd.set_option('display.max_rows', None)  
pd.set_option('display.max_colwidth', None)

address = input("Please enter the address: ")

from math import radians, sin, cos, sqrt, atan2

# calculates distance between user location & art location
def haversine(coord1, coord2):
    R = 6371000.0 

    lat1, lon1 = coord1 # point 1
    lat2, lon2 = coord2 # point 2

    dlat = radians(lat2 - lat1) # convert to radians
    dlon = radians(lon2 - lon1)
    
    # Haversine formula calculation
    # a calculates sine of half the difference in latitude squared 
    a = sin(dlat / 2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2)**2
    
    # c calculates angular distance between 2 points.
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    
    # multiply to Earth radius for distance of 2 points in metres
    return R * c


def get_coordinates_from_address(address, APIKEY):
    url = f"https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={APIKEY}"
    response = requests.get(url) # send GET request, 200 = successful
    if response.status_code == 200: 
        data = response.json() # parse json response 
        if data['status'] == 'OK':
            # extract latitude and longitude from json response 
            lat = data['results'][0]['geometry']['location']['lat']
            lng = data['results'][0]['geometry']['location']['lng']
            return lat, lng
    return None # if None meanins no results found



coordinates = get_coordinates_from_address(address, APIKEY)

Tree_df['Location'] = Tree_df['Location'].apply(lambda x: haversine(coordinates, x))

df_sorted = Tree_df.sort_values('distances')

# grabs closests 5 coordinates
closest_5_coordinates = Trep[['Common Name', 'Genus', 'Coordinates', 'distances']].head(5) 

# formats address from coordinates, uses Google API key
def get_address_from_coordinates(lat, lng, APIKEY):
    url = f"https://maps.googleapis.com/maps/api/geocode/json?latlng={lat},{lng}&key={APIKEY}"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        if data['status'] == 'OK':
            return data['results'][0]['formatted_address']
    return None

closest_5_coordinates['Address'] = closest_5_coordinates['Coordinates'].apply(lambda x: get_address_from_coordinates(x[0], x[1], api_key))

closest_5_coordinates['distances'] = closest_5_coordinates['distances'].apply(lambda x: f"{int(round(x))}m")

# format a link that when clicked, opens a new tab
def path_to_link(val):
    return f'<a href="{val}" target="_blank">{val}</a>'

# when the link is not in the City of Melbourne database. Search Google for a photo
def generate_link(title):
    title_formatted = title.replace(' ', '-')
    title_formatted = re.sub(r'[\[\]]', '-', title_formatted).lower()
    url = 'https://citycollection.melbourne.vic.gov.au/' + title_formatted + '/'
    response = requests.get(url)
    
    if response.status_code == 200:
        return url
    else:
        search_query = title_formatted + "-Melbourne-Art"
        search_url = "https://www.google.com/search?tbm=isch&q=" + search_query
        return search_url

closest_5_coordinates['Link'] = closest_5_coordinates['Title'].apply(generate_link)

display_columns = closest_5_coordinates[['Title', 'Description', 'Address', 'distances', 'Link']]
display_columns_styled = display_columns.style.format({'Link': path_to_link})

user_lat, user_lng = coordinates

# create folium map, centre to location of user
mymap = folium.Map(location=[user_lat, user_lng], zoom_start=25)

marker_locations = []

folium.TileLayer('cartodbdark_matter',overlay=False,name="View in Dark Mode").add_to(mymap)
folium.TileLayer('cartodbpositron',overlay=False,name="Viw in Light Mode").add_to(mymap)
folium.LayerControl(collapsed=False).add_to(mymap)


folium.Marker([user_lat, user_lng], tooltip='You are here', icon=folium.Icon(color='darkgreen', icon_color='white',prefix='fa',icon='person',extraClasses='fa-bounce')).add_to(mymap)

# create pins to form the closest art pieces from user location  
for index, row in closest_5_coordinates.iterrows():
    lat, lng = row['Coordinates']
    title = row['Title']
    address = row['Address']
    popup_text = f"<b>Address: <br>{address}</b>"
    

    marker_locations.append([lat, lng])
    
    folium.Marker([lat, lng], tooltip=title, popup=popup_text, icon =folium.Icon(color='green', icon_color='white',prefix='fa',icon='map-pin')
    ).add_to(mymap)
    
display(HTML(display_columns_styled.to_html()))
display(mymap)