In [16]:
#pip install folium
import pandas as pd
import numpy as np
import folium

from sodapy import Socrata

In [13]:
#folium.Map()
melb_city = folium.Map(location=[-37.818803,144.9630121], zoom_start=13, width=1000, height=600, control_scale=True)
melb_city

In [19]:
client = Socrata("data.melbourne.vic.gov.au", None)
results = client.get("h57g-5234")
results_df = pd.DataFrame.from_records(results)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [20]:
results_df

,sensor_id,sensor_description,sensor_name,installation_date,status,direction_1,direction_2,latitude,longitude,location,note
0,59,Building 80 RMIT,RMIT_T,2019-02-13T00:00:00.000,A,North,South,-37.80825648,144.96304859,"{'latitude': '-37.80825648', 'longitude': '144...",NaN
1,20,Chinatown-Lt Bourke St (South),LtB170_T,2013-09-06T00:00:00.000,A,East,West,-37.81172913,144.9682466,"{'latitude': '-37.81172913', 'longitude': '144...",NaN
2,34,Flinders St-Spark La,Fli32_T,2014-06-08T00:00:00.000,A,East,West,-37.81537985,144.9741505,"{'latitude': '-37.81537985', 'longitude': '144...",NaN
3,57,Bourke St Bridge,BouBri_T,2018-08-13T00:00:00.000,A,West,East,-37.8176735,144.95025595,"{'latitude': '-37.8176735', 'longitude': '144....",NaN
4,40,Lonsdale St-Spring St (West),Spr201_T,2015-01-19T00:00:00.000,A,South,North,-37.80999341,144.97227588,"{'latitude': '-37.80999341', 'longitude': '144...",NaN
...,...,...,...,...,...,...,...,...,...,...,...
67,21,Bourke St-Russell St (West),Rus180_T,2013-09-02T00:00:00.000,I,South,North,-37.81244703,144.96778757,"{'latitude': '-37.81244703', 'longitude': '144...",NaN
68,23,Spencer St-Collins St (South),Col623_T,2013-09-02T00:00:00.000,I,East,West,-37.81909256,144.95452749,"{'latitude': '-37.81909256', 'longitude': '144...",NaN
69,33,Flinders St-Spring St (West),Spr13_T,2014-04-23T00:00:00.000,R,North,South,-37.81483252,144.97454056,"{'latitude': '-37.81483252', 'longitude': '144...",NaN
70,13,Flagstaff Station,Wil277_T,2009-03-24T00:00:00.000,R,NaN,NaN,-37.81239679,144.95652653,"{'latitude': '-37.81239679', 'longitude': '144...",NaN
71,72,Flinders St- ACMI,ACMI_T,2020-11-30T00:00:00.000,A,East,West,-37.81726337,144.96872809,"{'latitude': '-37.81726337', 'longitude': '144...",NaN

In [23]:
# plot locations
for i in results_df:
    #folium.Marker(location=i[1], popup=i[0]).add_to(map_cities)
    print(i)

sensor_id
sensor_description
sensor_name
installation_date
status
direction_1
direction_2
latitude
longitude
location
note