# _**DELETE BEFORE PUBLISHING**_

_This is a template also containing the style guide for use cases. The styling uses the use-case css when uploaded to the website, which will not be visible on your local machine._

_Change any text marked with {} and delete any cells marked DELETE_

***

# Venuka Wijenayake

In [2]:
import requests
import pandas as pd
import os

def fetch_data(base_url, dataset, api_key, num_records=99, offset=0):
    all_records = []
    max_offset = 9900  # Maximum number of requests

    while True:
        # maximum limit check
        if offset > max_offset:
            break

        # Create API request URL
        filters = f'{dataset}/records?limit={num_records}&offset={offset}'
        url = f'{base_url}{filters}&api_key={api_key}'

        # Start request
        try:
            result = requests.get(url, timeout=10)
            result.raise_for_status()
            records = result.json().get('results')
        except requests.exceptions.RequestException as e:
            raise Exception(f"API request failed: {e}")
        if records is None:
            break
        all_records.extend(records)
        if len(records) < num_records:
            break

        # next cycle offset
        offset += num_records

    # DataFrame all data
    df = pd.DataFrame(all_records)
    return df

API_KEY = os.environ.get('MELBOURNE_API_KEY', input("Please enter your API key: "))
BASE_URL = 'https://data.melbourne.vic.gov.au/api/explore/v2.1/catalog/datasets/'

Please enter your API key:  a0d28c08580df90345c0c34846cf94b614eb5071d598c3b885237828

In [3]:
# data set name
PRE_COLONIAL_TREES = 'pre-colonial-plant-list'

pre_colonial_trees = fetch_data(BASE_URL, PRE_COLONIAL_TREES, API_KEY)

pre_colonial_trees

,species,common_name_s,certain,beach_and_dunes,saltmarsh,coastal_marshlands_and_brackish_flats,swamp_scrub,woodlands_and_heathlands_on_sand,woodlands_and_forests_on_sedimentary_hills_valleys_and_ridges,grasslands_and_woodlands_on_fertile_plains,cliffs_and_escarpments,river_banks_and_creeklines,wet_heathland,freshwater_wetland,saltwater_wetland,most_likely_occurrence,epbc_category_of_threat,ffg_extinction_risk,ffg_category_of_threat
0,Acacia mucronata var. longifolia,"Narrow-leaf Wattle, Variable Sallow Wattle",NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1.0,None,None,None
1,Acacia pycnantha,Golden Wattle,1.0,0.0,0.0,0.0,1.0,2.1,3.2,3.1,2.1,2.1,0.0,0.0,0,3.2,None,None,None
2,Acacia verticillata var. verticillata,Prickly Moses,NaN,0.0,0.0,0.0,3.1,3.1,0.0,0.0,0.0,3.1,1.0,0.0,0,3.1,None,None,None
3,Acaena echinata,Sheep's Burr,1.0,0.0,0.0,0.0,0.0,1.0,3.1,3.1,3.1,2.1,0.0,0.0,0,3.1,None,None,None
4,Acrotriche prostrata,Trailing Ground-Berry,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,Hovea heterophylla,"Common Hovea, Blue Bonnet, Bird's Eye",NaN,0.0,0.0,0.0,0.0,2.1,3.1,0.0,0.0,0.0,0.0,0.0,0,3.1,None,None,None
1063,Hydrocotyle foveolata,Yellow Pennywort,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1.0,None,None,None
1064,Hydrocotyle muscosa,Mossy Pennywort,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,1.0,None,None,None
1065,Hydrocotyle tripartita,Slender Pennywort,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.1,0.0,1.0,0,2.1,None,None,None
1066,Hydrocotyle verticillata,"Common Pennywort, Shield Pennywort",NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0,1.0,None,None,None

In [4]:
# data set name
CURRENT_TREES = 'trees-with-species-and-dimensions-urban-forest'

current_trees = fetch_data(BASE_URL, CURRENT_TREES, API_KEY)

current_trees

,com_id,common_name,scientific_name,genus,family,diameter_breast_height,year_planted,date_planted,age_description,useful_life_expectency,useful_life_expectency_value,precinct,located_in,uploaddate,coordinatelocation,latitude,longitude,easting,northing,geolocation
0,1546404,River Sheoak,Casuarina cunninghamiana,Casuarina,Casuarinaceae,NaN,2013,2013-01-07,None,None,NaN,None,Park,2021-01-10,"{'lon': 144.97177997020128, 'lat': -37.8180699...",-37.818070,144.971780,321479.34,5812432.31,"{'lon': 144.97177997020128, 'lat': -37.8180699..."
1,1038666,Claret Ash,Fraxinus angustifolia subsp. oxycarpa,Fraxinus,Oleaceae,26.0,1998,1998-11-09,Semi-Mature,11-20 years,20.0,None,Park,2021-01-10,"{'lon': 144.96069216093832, 'lat': -37.7815772...",-37.781577,144.960692,320414.93,5816460.51,"{'lon': 144.96069216093832, 'lat': -37.7815772..."
2,1439845,Kanooka,Tristaniopsis laurina,Tristaniopsis,Myrtaceae,NaN,2009,2009-09-08,None,None,NaN,None,Street,2021-01-10,"{'lon': 144.9455194257097, 'lat': -37.79259845...",-37.792598,144.945519,319105.53,5815208.27,"{'lon': 144.9455194257097, 'lat': -37.79259845..."
3,1070962,Spotted Gum,Corymbia maculata,Corymbia,Myrtaceae,17.0,2007,2007-06-14,Semi-Mature,31-60 years,60.0,None,Street,2021-01-10,"{'lon': 144.9421772126995, 'lat': -37.78013819...",-37.780138,144.942177,318780.78,5816584.46,"{'lon': 144.9421772126995, 'lat': -37.78013819..."
4,1066252,River red gum,Eucalyptus camaldulensis,Eucalyptus,Myrtaceae,19.0,2006,2006-02-20,Semi-Mature,61+ years,80.0,None,Street,2021-01-10,"{'lon': 144.92039340703647, 'lat': -37.7905765...",-37.790577,144.920393,316887.98,5815383.70,"{'lon': 144.92039340703647, 'lat': -37.7905765..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,1287372,Chinaberry Tree,Melia azedarach,Melia,Meliaceae,6.0,2008,2008-06-16,Juvenile,31-60 years,60.0,None,Street,2021-01-10,"{'lon': 144.96185487032108, 'lat': -37.8032135...",-37.803214,144.961855,320569.69,5814061.85,"{'lon': 144.96185487032108, 'lat': -37.8032135..."
9995,1064175,Yellow Box,Eucalyptus melliodora,Eucalyptus,Myrtaceae,NaN,2005,2005-12-29,None,None,NaN,None,Park,2021-01-10,"{'lon': 144.9542655755877, 'lat': -37.78508023...",-37.785080,144.954266,319857.44,5816059.43,"{'lon': 144.9542655755877, 'lat': -37.78508023..."
9996,1068611,Yellow Gum,Eucalyptus leucoxylon,Eucalyptus,Myrtaceae,NaN,2006,2006-10-24,None,None,NaN,None,Park,2021-01-10,"{'lon': 144.94969237020163, 'lat': -37.7774784...",-37.777478,144.949692,319436.19,5816894.14,"{'lon': 144.94969237020163, 'lat': -37.7774784..."
9997,1065473,River red gum,Eucalyptus camaldulensis,Eucalyptus,Myrtaceae,NaN,2006,2006-02-02,None,None,NaN,None,Park,2021-01-10,"{'lon': 144.9520802205775, 'lat': -37.78097001...",-37.780970,144.952080,319654.99,5816511.31,"{'lon': 144.9520802205775, 'lat': -37.78097001..."
9998,1021915,London Plane,Platanus x acerifolia,Platanus,Platanaceae,53.0,1997,1997-11-06,Mature,11-20 years,20.0,None,Street,2021-01-10,"{'lon': 144.96805266082373, 'lat': -37.7961241...",-37.796124,144.968053,321098.27,5814860.42,"{'lon': 144.96805266082373, 'lat': -37.7961241..."

## Step 1: Preprocess the Data

In [5]:
# DELETE BEFORE PUBLISHING
# This is just here so you can preview the styling on your local machine

from IPython.core.display import HTML
HTML("""
<style>
.usecase-title, .usecase-duration, .usecase-section-header {
    padding-left: 15px;
    padding-bottom: 10px;
    padding-top: 10px;
    padding-right: 15px;
    background-color: #0f9295;
    color: #fff;
}

.usecase-title {
    font-size: 1.7em;
    font-weight: bold;
}

.usecase-authors, .usecase-level, .usecase-skill {
    padding-left: 15px;
    padding-bottom: 7px;
    padding-top: 7px;
    background-color: #baeaeb;
    font-size: 1.4em;
    color: #121212;
}

.usecase-level-skill  {
    display: flex;
}

.usecase-level, .usecase-skill {
    width: 50%;
}

.usecase-duration, .usecase-skill {
    text-align: right;
    padding-right: 15px;
    padding-bottom: 8px;
    font-size: 1.4em;
}

.usecase-section-header {
    font-weight: bold;
    font-size: 1.5em;
}

.usecase-subsection-header, .usecase-subsection-blurb {
    font-weight: bold;
    font-size: 1.2em;
    color: #121212;
}

.usecase-subsection-blurb {
    font-size: 1em;
    font-style: italic;
}
</style>
""")

<div class="usecase-title">{Use Case Name}</div>

<div class="usecase-authors"><b>Authored by: </b> {Author/s}</div>

<div class="usecase-duration"><b>Duration:</b> {90} mins</div>

<div class="usecase-level-skill">
    <div class="usecase-level"><b>Level: </b>{Intermediate}</div>
    <div class="usecase-skill"><b>Pre-requisite Skills: </b>{Python, and add any more skills needed}</div>
</div>

<div class="usecase-section-header">Scenario</div>

{Using User Story format, write a description of the problem you are trying to solve for this use case.}

<div class="usecase-section-header">What this use case will teach you</div>

At the end of this use case you will:
- {list the skills demonstrated in your use case}

<div class="usecase-section-header">{Heading for introduction or background relating to problem}</div>

{Write your introduction here. Keep it concise. We're not after "War and Peace" but enough background information to inform the reader on the rationale for solving this problem or background non-technical information that helps explain the approach. You may also wish to give information on the datasets, particularly how to source those not being imported from the client's open data portal.}

***

_**DELETE BEFORE PUBLISHING**_

## Style guide for use cases

### Headers

For styling within your markdown cells, there are two choices you can use for headers.

1) You can use HTML classes specific to the use case styling:

```<p class="usecase-subsection-header">This is a subsection header.</p>```

<p style="font-weight: bold; font-size: 1.2em;">This is a subsection header.</p>

```<p class="usecase-subsection-blurb">This is a blurb header.</p>```

<p style="font-weight: bold; font-size: 1em; font-style:italic;">This is a blurb header.</p>


2) Or if you like you can use the markdown header styles:

```# for h1```

```## for h2```

```### for h3```

```#### for h4```

```##### for h5```

## Plot colour schemes

General advice:
1. Use the same colour or colour palette throughout your notebook, unless variety is necessary
2. Select a palette based on the type of data being represented
3. Consider accessibility (colourblindness, low vision)

#### 1) If all of your plots only use 1-2 colors use one of the company style colors:

| Light theme | Dark Theme |
|-----|-----|
|<p style="color:#2af598;">#2af598</p>|<p style="color:#08af64;">#08af64</p>|
|<p style="color:#22e4ac;">#22e4ac</p>|<p style="color:#14a38e;">#14a38e</p>|
|<p style="color:#1bd7bb;">#1bd7bb</p>|<p style="color:#0f9295;">#0f9295</p>|
|<p style="color:#14c9cb;">#14c9cb</p>|<p style="color:#056b8a;">#056b8a</p>|
|<p style="color:#0fbed8;">#0fbed8</p>|<p style="color:#121212;">#121212</p>|
|<p style="color:#08b3e5;">#08b3e5</p>||


#### 2) If your plot needs multiple colors, choose an appropriate palette using either of the following tutorials:
- https://seaborn.pydata.org/tutorial/color_palettes.html
- https://matplotlib.org/stable/tutorials/colors/colormaps.html

#### 3) Consider accessibility as well.

For qualitative plotting Seaborn's 'colorblind' palette is recommended. For maps with sequential or diverging it is recommended to use one of the Color Brewer schemes which can be previewed at https://colorbrewer2.org/.

If you want to design your own colour scheme, it should use the same principles as Cynthia Brewer's research (with variation not only in hue but also, saturation or luminance).

### References

Be sure to acknowledge your sources and any attributions using links or a reference list.

If you have quite a few references, you might wish to have a dedicated section for references at the end of your document, linked using footnote style numbers.

You can connect your in-text reference by adding the number with a HTML link: ```<a href="#fn-1">[1]</a>```

and add a matching ID in the reference list using the ```<fn>``` tag: ```<fn id="fn-1">[1] Author (Year) _Title_, Publisher, Publication location.</fn>```